// Every audit action the server writes, as the rows store it: the list the administrator's dashboard labels its
// security counts, its sensitive changes and its recent activity feed from, in Arabic and in English.
//
// The feed shows whatever a person or another system did last, so any action the server writes under a person's
// name can reach it, and every one needs a label. A row whose action had none would print the stored token, or the
// translation key, on the screen of the person whose job is to read it.
//
// TWO TESTS HOLD THE LIST TO THE TRUTH, one on each side of it. DashboardAuditActionLabelTests, in the backend's
// architecture tests, reads every audit write in the server's source and fails when an action it finds is missing
// here; it reads this file as text, so the list stays a plain array of string literals, one per line, with no
// entry built at runtime. The dynamic key coverage test in src/i18n fails when an action here has no label under
// dashboard.auditActions in either language.
//
// THE LABEL KEY IS THE ACTION WITH ITS DOTS TURNED INTO UNDERSCORES. Some actions are dotted, such as
// supplier.erp_push_retried and reference.currencies.created, and i18next reads a dot in a key as a step into a
// nested object, so the stored text cannot be the key as it is. No two actions turn into the same key, which the
// coverage test also checks.
//
// document_scan_requeued is written by the stuck-scan retry that shipped with the dashboard.
//
// The list runs in groups, in this order: signing in and the session's life, from SessionAuditActions; the
// account's own credentials and registration; staff administration, roles, keys and settings; the ERP connection,
// the import, the push and the exports read by other systems; a supplier's standing; onboarding review; the
// supplier's profile; documents; organisations; reference data, one set of four for each of the six tables;
// tenders; proposals; evaluation; and awards and the purchase order sent to the ERP. A blank line separates them.

export const DASHBOARD_AUDIT_ACTIONS = [
  'login_succeeded',
  'login_failed',
  'login_locked_out',
  'login_blocked_mfa_enrollment_required',
  'login_mfa_failed',
  'refresh_reuse_detected',
  'logout',
  'session_revoked',
  'sessions_revoked_all',

  'register',
  'state_change',
  'terms_accepted',
  'mfa_enrolled',
  'password_changed',
  'password_change_refused',
  'password_reset',

  'staff_invited',
  'staff_role_changed',
  'staff_deactivated',
  'staff_reactivated',
  'staff_mfa_reset',
  'role_permissions_updated',
  'api_key_created',
  'api_key_revoked',
  'setting.updated',
  'notification.template.updated',
  'notification.template.reverted',

  'IntegrationConnectionUpdated',
  'IntegrationSupplierCreationChanged',
  'IntegrationConnectionTested',
  'ErpImportPreviewed',
  'ErpImportRun',
  'ErpImportCompleted',
  'ErpImportFailed',
  'supplier.imported_from_erp',
  'supplier.suspended_missing_from_erp',
  'supplier.suspended_disabled_in_erp',
  'supplier.suspended_not_approved_in_erp',
  'supplier.marked_removed_from_erp',
  'supplier.marked_disabled_in_erp',
  'supplier.marked_not_approved_in_erp',
  'supplier.reactivated_approved_in_erp',
  'supplier.erp_release_withdrawn',
  'supplier.erp_push_created',
  'supplier.erp_push_completed',
  'supplier.erp_push_attempt_failed',
  'supplier.erp_push_failed',
  'supplier.erp_push_retried',
  'SupplierRegistryExported',
  'MinistrySupplierFeedExported',
  'MinistryRfqFeedExported',

  'supplier_suspended',
  'supplier_reactivated',
  'supplier_deactivated',
  'supplier_kept_suspended',
  'supplier_auto_suspended',
  'supplier_auto_reinstated',
  'compliance_field_changed_review_retriggered',

  'application_submitted',
  'application_resubmitted',
  'application_claimed',
  'application_picked_up',
  'application_unassigned',
  'application_review_resumed',
  'application_info_requested',
  'application_approved',
  'application_rejected',

  'profile_updated',
  'legal_info_updated',
  'logo_uploaded',
  'primary_category_set',
  'category_linked',
  'category_unlinked',
  'address_added',
  'address_updated',
  'address_removed',
  'contact_added',
  'contact_updated',
  'contact_removed',
  'representative_added',
  'representative_updated',
  'representative_removed',
  'representative_set_primary',
  'branch_added',
  'branch_updated',
  'branch_removed',
  'bank_account_added',
  'bank_account_updated',
  'bank_account_removed',
  'bank_account_set_default',
  'bank_account_revealed',
  'offering_created',
  'offering_updated',
  'offering_deactivated',
  'supplier_user_invited',
  'supplier_user_disabled',

  'document_uploaded',
  'document_upload_content_mismatch',
  'document_scan_clean',
  'document_scan_rejected',
  'document_scan_requeued',
  'document_approved',
  'document_rejected',
  'document_expiring_soon',
  'document_expired',
  'document_access_granted',
  'draft_cleanup_deleted',

  'organization_created',
  'organization_link_created',
  'organization_link_removed',
  'org_unit_added',
  'org_unit_removed',

  'reference.categories.created',
  'reference.categories.updated',
  'reference.categories.deactivated',
  'reference.categories.reactivated',
  'reference.document-types.created',
  'reference.document-types.updated',
  'reference.document-types.deactivated',
  'reference.document-types.reactivated',
  'reference.currencies.created',
  'reference.currencies.updated',
  'reference.currencies.deactivated',
  'reference.currencies.reactivated',
  'reference.units-of-measure.created',
  'reference.units-of-measure.updated',
  'reference.units-of-measure.deactivated',
  'reference.units-of-measure.reactivated',
  'reference.regions.created',
  'reference.regions.updated',
  'reference.regions.deactivated',
  'reference.regions.reactivated',
  'reference.incoterms.created',
  'reference.incoterms.updated',
  'reference.incoterms.deactivated',
  'reference.incoterms.reactivated',

  'rfq_created',
  'rfq_updated',
  'rfq_item_added',
  'rfq_item_updated',
  'rfq_item_removed',
  'rfq_requirement_added',
  'rfq_requirement_updated',
  'rfq_requirement_removed',
  'rfq_attachment_added',
  'rfq_attachment_removed',
  'rfq_attachment_scan_rejected',
  'rfq_attachment_access_granted',
  'rfq_evaluation_template_bound',
  'rfq_submitted_for_review',
  'rfq_returned',
  'rfq_approved',
  'rfq_published',
  'rfq_supplier_invited',
  'rfq_invitation_viewed',
  'rfq_invitation_declined',
  'rfq_addendum_issued',
  'rfq.deadline_extended',
  'rfq.deadline_shortened',
  'rfq_clarification_posted',
  'rfq_clarification_requested',
  'rfq_clarification_answered',
  'rfq_clarification_published',
  'rfq_clarification_resolved',
  'rfq_reassigned',
  'rfq_submission_opened',
  'rfq_submission_closed',
  'rfq_shortlisting_started',
  'rfq_evaluation_opened',
  'rfq_recommendation_recorded',
  'rfq.returned_to_recommendation',
  'rfq_awarded',
  'rfq_completed',
  'rfq_cancelled',

  'proposal_started',
  'proposal_item_priced',
  'proposal_item_removed',
  'proposal_terms_updated',
  'proposal_narrative_updated',
  'proposal_requirement_answered',
  'proposal_document_added',
  'proposal_document_removed',
  'proposal_document_scan_rejected',
  'proposal_document_access_granted',
  'proposal_submitted',
  'proposal_revised',
  'proposal_withdrawn',
  'proposal_cancelled',
  'proposal_lapsed',
  'proposal_under_review',
  'proposal_clarification_requested',
  'proposal_shortlisted',
  'proposal.award_offered',
  'proposal.awarded',
  'proposal.declined',
  'proposal.not_selected',

  'evaluation_template_created',
  'evaluation_template_forked',
  'evaluation_template_activated',
  'evaluation_template_archived',
  'criterion_added',
  'criterion_updated',
  'criterion_removed',
  'evaluation_created',
  'evaluation_evaluators_assigned',
  'evaluator_declared_no_conflict',
  'evaluator_self_recused',
  'evaluation_evaluator_recused',
  'evaluation.scoring_started',
  'evaluation.score',
  'evaluation_evaluator_submitted',
  'evaluation_consolidated',
  'evaluation_tie_resolved',
  'evaluation_finalized',
  'evaluation_reopened',

  'award.recommended',
  'award.re_recommended',
  'award.pending_approval',
  'award.approved',
  'award.rejected',
  'award.awarded',
  'award.erp_po_synced',
  'award.erp_po_failed',
  'award.erp_po_retried',
] as const

export type DashboardAuditAction = (typeof DASHBOARD_AUDIT_ACTIONS)[number]

export function dashboardAuditActionKey(action: string): string {
  return action.replaceAll('.', '_')
}
