// How a tender maps to its table, its search vector, and the index its dashboards need.
//
// The search vector works the way the supplier's does; that file explains why it is generated by the
// database and why it uses the unstemmed configuration.
//
// The owner index is composite rather than a bare index on the owner alone, because the awaiting-my-action
// view and the buyer list's mine-or-unassigned filter both query on the owner beside the organization,
// and the organization is already the first clause of every dashboard query.

namespace MotsSupplierPortal.Infrastructure.Persistence.Configurations;

using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore;
using MotsSupplierPortal.Domain.Rfqs;

internal sealed class RfqConfiguration : IEntityTypeConfiguration<Rfq>
{
    public void Configure(EntityTypeBuilder<Rfq> entity)
    {
        entity.ToTable("rfq", "rfq");
        entity.Property<NpgsqlTypes.NpgsqlTsVector>("SearchVector")
            .HasComputedColumnSql(
                "to_tsvector('simple', regexp_replace(coalesce(\"TitleAr\",'') || ' ' || coalesce(\"TitleEn\",'') || ' ' || coalesce(\"ReferenceCode\",''), '[^[:alnum:]]+', ' ', 'g'))",
                stored: true);
        entity.HasIndex("SearchVector").HasMethod("GIN");
        entity.HasKey(r => r.Id);
        entity.Property(r => r.ReferenceCode).HasMaxLength(30).IsRequired();
        entity.HasIndex(r => r.ReferenceCode).IsUnique();
        entity.Property(r => r.TitleAr).HasMaxLength(300).IsRequired();
        entity.Property(r => r.TitleEn).HasMaxLength(300).IsRequired();
        entity.Property(r => r.DescriptionAr).HasMaxLength(4000);
        entity.Property(r => r.DescriptionEn).HasMaxLength(4000);
        entity.Property(r => r.CurrencyCode).HasMaxLength(3).IsRequired();
        entity.Property(r => r.State).HasConversion<string>().HasMaxLength(20);
        entity.Property(r => r.EvaluationTemplateSnapshotJson).HasColumnType("jsonb");
        entity.Property(r => r.CancelReason).HasMaxLength(2000);
        entity.Property(r => r.RowVersion).IsAppManagedVersion();
        entity.HasIndex(r => new { r.OrganizationId, r.State });
        entity.HasIndex(r => r.State);
        entity.HasIndex(r => new { r.OrganizationId, r.OwnerUserId });
        entity.HasMany(r => r.Items).WithOne().HasForeignKey(i => i.RfqId).OnDelete(DeleteBehavior.Cascade);
        entity.HasMany(r => r.Requirements).WithOne().HasForeignKey(q => q.RfqId).OnDelete(DeleteBehavior.Cascade);
        entity.HasMany(r => r.Attachments).WithOne().HasForeignKey(a => a.RfqId).OnDelete(DeleteBehavior.Cascade);
        entity.HasMany(r => r.Approvals).WithOne().HasForeignKey(a => a.RfqId).OnDelete(DeleteBehavior.Cascade);
        entity.HasMany(r => r.Invitations).WithOne().HasForeignKey(i => i.RfqId).OnDelete(DeleteBehavior.Cascade);
        entity.HasMany(r => r.Clarifications).WithOne().HasForeignKey(c => c.RfqId).OnDelete(DeleteBehavior.Cascade);
        entity.HasMany(r => r.Addenda).WithOne().HasForeignKey(a => a.RfqId).OnDelete(DeleteBehavior.Cascade);
    }
}
