namespace MotsSupplierPortal.Api.Authorization;

/// <summary>
/// Enforces a resource.action permission claim at the API (STORY-01.7.1). The UI re-checks the
/// same permission solely to hide affordances - it is never the source of truth.
/// </summary>
public sealed class PermissionEndpointFilter(params string[] permissions) : IEndpointFilter
{
    public async ValueTask<object?> InvokeAsync(EndpointFilterInvocationContext context, EndpointFilterDelegate next)
    {
        var user = context.HttpContext.User;
        if (user.Identity?.IsAuthenticated != true)
        {
            return Results.Unauthorized();
        }

        // ANY of the listed permissions, and the list is normally one.
        //
        // The multi-permission form exists for a read whose audience is wider than its writes: listing
        // evaluation templates is needed by anyone who may BIND one to a tender (rfq.edit) as well as by
        // whoever maintains them (evaluation.template.manage). Gating the read on the management
        // permission alone left a procurement officer able to bind a template they could not see, so
        // the list came back 403 and the tender could not reach internal review at all.
        var hasPermission = user.Claims.Any(c => c.Type == "perms" && permissions.Contains(c.Value));
        if (!hasPermission)
        {
            return Results.Forbid();
        }

        return await next(context);
    }
}

/// <summary>
/// "This route requires one of these permissions", on the endpoint table.
///
/// <para><b>Why the requirement is metadata as well as a filter.</b> A filter is invisible to anything that
/// does not send a request, so nothing could ask the application which permission gates which route -
/// <c>PERMISSIONS.md</c> is generated by REGEX over the Api's own source for exactly that reason. NFR-SEC-004's
/// authorisation sweep needs the same fact at runtime: to check that a role WITHOUT a permission is refused,
/// a test has to know what each route wants, and reading it off the endpoint is the only way that cannot
/// drift from what the filter enforces.</para>
/// </summary>
public sealed class RequiredPermissionsMetadata(params string[] permissions)
{
    /// <summary>Any ONE of these admits the caller - the same "any" the filter applies.</summary>
    public IReadOnlyList<string> Permissions { get; } = permissions;
}

public static class RequirePermissionExtensions
{
    public static RouteHandlerBuilder RequirePermission(this RouteHandlerBuilder builder, string permission) =>
        builder
            .AddEndpointFilter(new PermissionEndpointFilter(permission))
            .WithMetadata(new RequiredPermissionsMetadata(permission))
            .RequireAuthorization();

    /// <summary>Passes when the caller holds ANY of these. For a read that several roles legitimately
    /// need while its writes stay narrower - see the filter's own comment.</summary>
    public static RouteHandlerBuilder RequireAnyPermission(this RouteHandlerBuilder builder, params string[] permissions) =>
        builder
            .AddEndpointFilter(new PermissionEndpointFilter(permissions))
            .WithMetadata(new RequiredPermissionsMetadata(permissions))
            .RequireAuthorization();

    /// <summary>Group-level variant for an endpoint group where every route shares the same
    /// permission (e.g. EvaluationTemplateEndpoints) - equivalent to applying the single-route
    /// overload to each MapGet/MapPost/etc. individually, just without repeating it per route.</summary>
    public static RouteGroupBuilder RequirePermission(this RouteGroupBuilder builder, string permission) =>
        builder
            .AddEndpointFilter(new PermissionEndpointFilter(permission))
            .WithMetadata(new RequiredPermissionsMetadata(permission))
            .RequireAuthorization();
}
