import { defineConfig, mergeConfig } from 'vitest/config'
import viteConfig from './vite.config.ts'

/**
 * MSP-70: frontend coverage measurement.
 *
 * vitest was already a devDependency but had no config, no `test` script, and no test files - so
 * the frontend contributed nothing to the coverage number and its absence was invisible.
 *
 * The point of this config was to make the real number visible rather than to report a good one:
 * roughly 5,300 lines of TypeScript with no unit tests behind them, showing up in the gate as a gap
 * rather than as silence. It did. There are 118 test files now and the frontend sits above 82%.
 *
 * This paragraph said "there are currently ZERO frontend unit tests" for as long as there were a
 * hundred of them. It is left here corrected rather than deleted because the reason the config
 * exists is still the reason it exists, and a file that records why it was written is worth more
 * than one that only records what it does.
 */
export default mergeConfig(
  viteConfig,
  defineConfig({
    test: {
      environment: 'jsdom',
      setupFiles: ['./vitest.setup.ts'],
      globals: true,
      include: ['src/**/*.{test,spec}.{ts,tsx}'],
      // Playwright drives a real browser and owns its own runner; letting vitest collect these
      // would start them a second time under jsdom, where they cannot pass.
      exclude: ['tests/e2e/**', 'node_modules/**', 'dist/**'],

      // There are no test files yet. Without this the run exits non-zero and CI fails on a
      // condition that is already known and already reported by the coverage number - a red build
      // that teaches nothing. The zero is surfaced through coverage instead, where it is a
      // measurement rather than an error.
      //
      // Kept now for a different reason than it was added for: a filter that matches nothing - a
      // renamed directory, a changed `include` - would otherwise fail loudly, which sounds better
      // and is not. It fails the same way whether the cause is zero tests or a broken glob, and
      // this repository has been caught by that shape before. The instrument that would catch it is
      // the coverage number dropping, which is watched.
      passWithNoTests: true,

      coverage: {
        provider: 'v8',
        // `all: true` is the setting that matters here. Without it, coverage is computed only over
        // files some test imported - so with zero tests the report would be empty, Sonar would see
        // no frontend coverage data at all, and the frontend would silently vanish from the
        // denominator. That is the exact failure this ticket exists to remove: a number that looks
        // acceptable because a large untested surface is invisible rather than because it is
        // tested. With `all`, every source file is included at 0% until something covers it.
        all: true,
        include: ['src/**/*.{ts,tsx}'],
        exclude: [
          'src/**/*.stories.tsx',      // Storybook fixtures, not shipped behaviour
          'src/**/*.d.ts',
          'src/main.tsx',              // bootstrap; mirrors the backend's Program.cs exclusion
          'src/routeTree.gen.ts',      // generated by TanStack Router
        ],
        // lcov is what the Sonar scanner consumes; text-summary is for a human reading CI logs.
        reporter: ['text-summary', 'lcov'],
        reportsDirectory: './coverage',
      },
    },
  }),
)
