import { defineConfig, mergeConfig } from 'vitest/config'
import viteConfig from './vite.config.ts'

/**
 * MSP-70: frontend coverage measurement.
 *
 * vitest was already a devDependency but had no config, no `test` script, and no test files - so
 * the frontend contributed nothing to the coverage number and its absence was invisible. There are
 * currently ZERO frontend unit tests; the two files under tests/e2e are Playwright specs, which
 * exercise the app through a browser and produce no coverage data.
 *
 * The point of this config is therefore not to report a good number. It is to make the real one
 * visible: roughly 5,300 lines of TypeScript with no unit tests behind them. That is a genuine gap,
 * and it should show up in the gate as a gap rather than as silence.
 */
export default mergeConfig(
  viteConfig,
  defineConfig({
    test: {
      environment: 'jsdom',
      setupFiles: ['./vitest.setup.ts'],
      globals: true,
      include: ['src/**/*.{test,spec}.{ts,tsx}'],
      // Playwright drives a real browser and owns its own runner; letting vitest collect these
      // would start them a second time under jsdom, where they cannot pass.
      exclude: ['tests/e2e/**', 'node_modules/**', 'dist/**'],

      // There are no test files yet. Without this the run exits non-zero and CI fails on a
      // condition that is already known and already reported by the coverage number - a red build
      // that teaches nothing. The zero is surfaced through coverage instead, where it is a
      // measurement rather than an error. Remove this once the first test lands.
      passWithNoTests: true,

      coverage: {
        provider: 'v8',
        // `all: true` is the setting that matters here. Without it, coverage is computed only over
        // files some test imported - so with zero tests the report would be empty, Sonar would see
        // no frontend coverage data at all, and the frontend would silently vanish from the
        // denominator. That is the exact failure this ticket exists to remove: a number that looks
        // acceptable because a large untested surface is invisible rather than because it is
        // tested. With `all`, every source file is included at 0% until something covers it.
        all: true,
        include: ['src/**/*.{ts,tsx}'],
        exclude: [
          'src/**/*.stories.tsx',      // Storybook fixtures, not shipped behaviour
          'src/**/*.d.ts',
          'src/main.tsx',              // bootstrap; mirrors the backend's Program.cs exclusion
          'src/routeTree.gen.ts',      // generated by TanStack Router
        ],
        // lcov is what the Sonar scanner consumes; text-summary is for a human reading CI logs.
        reporter: ['text-summary', 'lcov'],
        reportsDirectory: './coverage',
      },
    },
  }),
)
